#profile_img: assets/img/profile.webp
icon_img: assets/img/icon.webp

name: "Vighnesh Challa"
job: "Data Scientist"

phone_number: +91 - 7845356123
address: Hyderabad, India
email: challavighnesh@hotmail.co.in
linkedin_username: vighneshchalla
github_username: vighneshch
remote_theme: byanko55/jekyll-professional-resume
plugins:
- jekyll-remote-theme
