title: "Vighnesh Challa"
description: Dive into my Data Science portfolio featuring cutting-edge Deep Learning and NLP projects.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme


